# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: review_api_development
test:
  <<: *default
  database: review_api_test
production:
  <<: *default
  database: review_api_production
  username: review_api
  password: <%= ENV['REVIEW_API_DATABASE_PASSWORD'] %>
